POST https://node-do-zerp.onrender.com/videos
Content-Type: application/json

{
    "title": "JavaScript Arrays and String Methods",
    "description": "Esse é o primeiro video",
    "duration": 200
}


###

GET https://node-do-zerp.onrender.com/videos

### search
GET https://node-do-zerp.onrender.com/videos?search=node


###

PUT https://node-do-zerp.onrender.com/videos/4a724d4c-76b7-4532-8b13-9c6d54a0f973
Content-Type: application/json

{
    "title": "Video from Direct",
    "description": "This video.....",
    "duration": 180
}

###

DELETE https://node-do-zerp.onrender.com/videos/8cac810c-484d-44e9-93ef-d97d90542196	

